### PR TITLE
Upgrade pyo3 to 0.14.1

### PR DESCRIPTION
**Pull request by messense**
Also upgraded `zstd` to `0.9.0+zstd.1.5.0` along the way.

### CODE REVIEW

**Comment by messense** [comment]
> SystemError: Bad call flags in PyCFunction_Call. METH_OLDARGS is no longer supported!

Get an odd error with Python 3.6 only on macOS. Looks like https://bugs.python.org/issue11587 , I don't know how to deal with it. cc @davidhewitt

**Comment by messense** [comment]
Failed to reproduce the failures on x86_64 macOS Big Sur 11.4 with Python 3.6.14.

**Comment by davidhewitt** [comment]
Is it possible that pyO3 has configured the build against a newer Python version and then runs against 3.6?

I'll try to put together a script to help understand that. We could also add an exception in module init if running with an incorrect interpreter, I guess.

**Comment by messense** [comment]
Looks like it's somehow related to how we build universal2 wheel: https://github.com/messense/maturin-action/blob/88d9d95e56d823e7981ae520d80261ed5e72e990/src/index.ts#L409-L410

Python 3.6 and 3.7 are not supported on Apple Silicon Macs anyway so I've removed universal2 wheels from them.

**Review by milesgranger — APPROVED** [review]
Appreciate the help! :100:

**Pull request merged**
