### PR TITLE
Clippy and benchmark work

### PR DESCRIPTION
**Pull request by milesgranger**

### CODE REVIEW

**Comment by milesgranger** [comment]
@martindurant
I would like to get your thoughts on the updated benchmark for snappy raw. I attempted to link directly to snappy c API (exactly the same as python-snappy uses) and got roughly the same benchmarks as with the pure rust implementation; which as you know seems to be slightly slower than python-snappy. 

So I dug into python-snappy a bit, and it seems it uses `cffi.FFI.buffer` to point to the results, [according to the documentation for that:](https://cffi.readthedocs.io/en/latest/ref.html?highlight=buffer#ffi-buffer-ffi-from-buffer)
> object that references the raw C data pointed to by the given ‘cdata’, of ‘size’ bytes. What Python calls “a buffer”, or more precisely “an object supporting the buffer interface”, is an object that represents some raw memory and that can be passed around to various built-in or extension functions; these built-in functions read from or write to the raw memory directly, without needing an extra copy.

I interpret this as, once the compression has occurred, there is no reallocation done to pass it back as whatever it got in as we do here in cramjam using `PyBytes` and `PyByteArray`; so I've updated the benchmark to use `cramjam.Buffer` and the result there are just as good IMO, as it is more in line with the allocations/operations going on:

```
------------------------------------------------------------------------------------------------------------ benchmark: 28 tests -------------------------------------------------------------------------------------------------------------
Name (time in us)                                              Min                    Max                   Mean              StdDev                 Median                 IQR            Outliers          OPS            Rounds  Iterations
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_snappy_raw[Mark.Twain-Tom.Sawyer.txt-cramjam]         58.2180 (3.84)        135.9810 (2.53)         60.8318 (3.82)       7.3073 (3.53)         58.9310 (3.79)       0.4360 (2.83)      492;805  16,438.7631 (0.26)       6330           1
test_snappy_raw[Mark.Twain-Tom.Sawyer.txt-snappy]          52.7840 (3.48)        125.1060 (2.33)         55.6338 (3.49)       6.8327 (3.30)         53.7610 (3.46)       0.4900 (3.18)    1018;1376  17,974.6966 (0.29)      11454           1
test_snappy_raw[alice29.txt-cramjam]                      620.2070 (40.92)       832.4800 (15.51)       642.5410 (40.31)     34.3773 (16.59)       623.1925 (40.09)     25.8150 (167.64)    166;137   1,556.3209 (0.02)       1416           1
test_snappy_raw[alice29.txt-snappy]                       600.1930 (39.60)       874.8200 (16.30)       622.1477 (39.03)     34.5308 (16.67)       604.4980 (38.89)     23.0438 (149.65)    158;146   1,607.3354 (0.03)       1513           1
test_snappy_raw[asyoulik.txt-cramjam]                     549.5720 (36.26)       729.5570 (13.59)       566.7486 (35.55)     26.5494 (12.81)       552.5450 (35.54)     21.1373 (137.27)    185;138   1,764.4508 (0.03)       1563           1
test_snappy_raw[asyoulik.txt-snappy]                      532.3900 (35.13)       698.7550 (13.02)       549.9556 (34.50)     24.6149 (11.88)       536.7260 (34.53)     21.1555 (137.38)    198;113   1,818.3285 (0.03)       1461           1
test_snappy_raw[fifty-four-mb-random-cramjam]          49,416.9960 (>1000.0)  49,819.3310 (928.30)   49,628.8115 (>1000.0)  106.1064 (51.22)    49,640.6510 (>1000.0)   88.3850 (573.97)        3;2      20.1496 (0.00)         10           1
test_snappy_raw[fifty-four-mb-random-snappy]           49,827.5210 (>1000.0)  51,307.8900 (956.04)   50,777.3246 (>1000.0)  464.8408 (224.37)   50,869.3570 (>1000.0)  351.1065 (>1000.0)       6;4      19.6938 (0.00)         21           1
test_snappy_raw[fifty-four-mb-repeating-cramjam]       24,555.5240 (>1000.0)  25,791.6320 (480.59)   24,856.6676 (>1000.0)  302.7096 (146.11)   24,834.2305 (>1000.0)  254.6600 (>1000.0)       1;1      40.2307 (0.00)         14           1
test_snappy_raw[fifty-four-mb-repeating-snappy]        28,908.3110 (>1000.0)  29,721.9840 (553.82)   29,249.9480 (>1000.0)  199.8443 (96.46)    29,227.3050 (>1000.0)  260.0938 (>1000.0)      11;0      34.1881 (0.00)         35           1
test_snappy_raw[fireworks.jpeg-cramjam]                    46.0100 (3.04)         91.8140 (1.71)         47.6696 (2.99)       4.7781 (2.31)         46.3970 (2.98)       0.1680 (1.09)      646;891  20,977.7336 (0.33)       8245           1
test_snappy_raw[fireworks.jpeg-snappy]                     15.1560 (1.0)          53.6670 (1.0)          15.9403 (1.0)        2.0717 (1.0)          15.5450 (1.0)        0.3120 (2.03)    1245;1874  62,733.9199 (1.0)       32850           1
test_snappy_raw[geo.protodata-cramjam]                    170.3450 (11.24)       333.4490 (6.21)        177.0886 (11.11)     15.0165 (7.25)        171.8390 (11.05)      0.8470 (5.50)      434;858   5,646.8903 (0.09)       4538           1
test_snappy_raw[geo.protodata-snappy]                     143.3340 (9.46)        233.0740 (4.34)        150.5559 (9.44)      12.6989 (6.13)        146.8010 (9.44)       2.0495 (13.31)     607;966   6,642.0506 (0.11)       5885           1
test_snappy_raw[html-cramjam]                             178.2480 (11.76)       313.7720 (5.85)        185.5136 (11.64)     15.8938 (7.67)        179.8720 (11.57)      0.7817 (5.08)      382;825   5,390.4401 (0.09)       4141           1
test_snappy_raw[html-snappy]                              156.4810 (10.32)       291.1800 (5.43)        163.3853 (10.25)     14.6697 (7.08)        158.1690 (10.17)      0.8953 (5.81)     593;1096   6,120.5018 (0.10)       5789           1
test_snappy_raw[html_x_4-cramjam]                         701.4040 (46.28)       972.5600 (18.12)       727.3056 (45.63)     38.8320 (18.74)       706.4060 (45.44)     31.2620 (203.02)     110;92   1,374.9379 (0.02)        962           1
test_snappy_raw[html_x_4-snappy]                          634.5480 (41.87)       933.0780 (17.39)       662.2940 (41.55)     45.3220 (21.88)       639.9740 (41.17)     29.3398 (190.53)    158;150   1,509.9035 (0.02)       1437           1
test_snappy_raw[kppkn.gtb-cramjam]                        521.9650 (34.44)       793.0800 (14.78)       538.4331 (33.78)     29.3966 (14.19)       523.3415 (33.67)     20.6910 (134.37)    175;157   1,857.2408 (0.03)       1686           1
test_snappy_raw[kppkn.gtb-snappy]                         504.1280 (33.26)       697.3310 (12.99)       523.2445 (32.83)     33.1399 (16.00)       506.2950 (32.57)     20.9355 (135.96)    204;197   1,911.1523 (0.03)       1821           1
test_snappy_raw[lcet10.txt-cramjam]                     1,632.4170 (107.71)    2,242.8980 (41.79)     1,683.4017 (105.61)    57.4938 (27.75)     1,661.5140 (106.88)    64.4040 (418.24)      83;13     594.0353 (0.01)        530           1
test_snappy_raw[lcet10.txt-snappy]                      1,589.9350 (104.90)    1,925.9060 (35.89)     1,637.0257 (102.70)    48.8167 (23.56)     1,619.6890 (104.19)    59.1820 (384.33)      76;24     610.8640 (0.01)        573           1
test_snappy_raw[paper-100k.pdf-cramjam]                    45.2860 (2.99)        105.2450 (1.96)         47.0243 (2.95)       5.1940 (2.51)         45.6320 (2.94)       0.1540 (1.0)      848;1181  21,265.5986 (0.34)      10384           1
test_snappy_raw[paper-100k.pdf-snappy]                     19.9690 (1.32)         54.4530 (1.01)         21.2500 (1.33)       2.8024 (1.35)         20.6300 (1.33)       0.2540 (1.65)     767;1665  47,058.8712 (0.75)      14249           1
test_snappy_raw[plrabn12.txt-cramjam]                   2,230.6450 (147.18)    2,580.8280 (48.09)     2,312.9307 (145.10)    76.2218 (36.79)     2,285.8300 (147.05)    93.5695 (607.64)      90;11     432.3519 (0.01)        316           1
test_snappy_raw[plrabn12.txt-snappy]                    2,315.2640 (152.76)    2,813.5330 (52.43)     2,391.2336 (150.01)    71.5417 (34.53)     2,367.4420 (152.30)    85.5890 (555.81)      96;10     418.1942 (0.01)        409           1
test_snappy_raw[urls.10K-cramjam]                       1,925.7170 (127.06)    2,287.4900 (42.62)     2,003.1727 (125.67)    76.8316 (37.09)     1,977.0500 (127.18)   102.6413 (666.55)       56;7     499.2081 (0.01)        349           1
test_snappy_raw[urls.10K-snappy]                        1,936.4490 (127.77)    2,305.1690 (42.95)     1,997.1872 (125.29)    62.1015 (29.98)     1,976.7030 (127.16)    79.9700 (519.32)      80;16     500.7042 (0.01)        494           1
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

I'm fine leaving it the other way, as I guess from an API standpoint current benchmarks reflect real differences using the same API interface; but maybe you're interested in this anyhow.

**Comment by martindurant** [comment]
It is good to see that the performance is essentially the same. 

If the difference is the passing of a python buffer object pointing to existing allocated memory, this raises the question: can't you do this for rust too? Indeed, when we know the size, the buffer could be allocated by python (as a bytearray maybe) and passed in, so rust doesn't need to worry about ownership.

**Comment by milesgranger** [comment]
If one adjusts the benchmark to instead:
```python
    data = file.read_bytes()
    compressed_len = len(cramjam.snappy.compress_raw(data))
    compressed = b'0' * compressed_len
    decompressed = b'0' * len(data)

    def _roundtrip():
        cramjam.snappy.compress_raw_into(data, compressed)
        cramjam.snappy.decompress_raw_into(compressed, decompressed)
```

You'll get basically the same results. Is this what you meant by buffer be allocated by python and rust doesn't worry about ownership? I think that checks all the boxes.

**Comment by martindurant** [comment]
I am confused, though - snappy-python *does* allocate a buffer at some point, and that is included in the benchmark, right? So it seems incorrect to compare with the above, where the allocation is outside of the benchmark.

**Comment by milesgranger** [comment]
And that's why I'm not including it in the benchmarks, from the API point of view, it's slower, _in the benchmarks_.

However, I find it exceedingly suspicious that, when preallocating them outside the benchmark, the results aren't _way_ better but basically the same as python-snappy; and when putting them _in_ the benchmark makes it's just mildly worse. I wouldn't be surprised if Python is re-using the buffer(s) created by python-snappy during the first go round.  As I've mentioned, linking to the snappy lib directly in Rust gets me _very_ similar results, so at this point, I feel it's not a Rust vs C implementation; there is something else at play here. Could be some clever re-use of non-garbage collected buffers, or maybe the overhead of PyO3 creating native Python objects. Either way, it seems like something outside of my control AFAIK.

Anyway, the main thing here was more of a point of interest, because as you said, you know the output length and have pre-allocated buffers, so _in practice_, the current implementation is just as fast as I see it.

**Comment by martindurant** [comment]
> I wouldn't be surprised if Python is re-using the buffer(s) created by python-snappy during the first go round.

Python definitely does reuse memory rather than free/malloc on every gc/assign loop

**Pull request closed without merging**
