### PR TITLE
Support lz4 block format

### PR DESCRIPTION
**Pull request by milesgranger**
To help with https://github.com/dask/fastparquet/pull/580

### CODE REVIEW

**Comment by martindurant** [comment]
benchmarks look good

**Comment by milesgranger** [comment]
This will add block format for lz4, but not (yet) `_into` options as lz4 doesn't support compression into slices, only outputting new Vecs.

There is a possibility `_into`s could be added later as lz4_flex may be adding this API in the future, trade off there being no guarantee their the API would follow a similar Python API as lz4 crate does now; so would almost certainly require re-implementing the `store_size` component. Could always get creative and use some `unsafe` code to trick whatever slice we have into a `Vec` if it's _really_ desired; as I'm pretty sure lz4 crate won't be chaining its API anytime soon; but [have opened an issue anyway](https://github.com/10XGenomics/lz4-rs/issues/16)

**Comment by milesgranger** [comment]
@martindurant is this good with you?  I'll come back for the `_into`s depending on what becomes of that issue I made.

**Comment by martindurant** [comment]
Yes, totally good.
It turns out there is also a hadoop-specific version of lz4 that was used by map-reduce, but I think we can safely ignore it.

**Pull request merged**
