### PR TITLE
Backlog: Support streaming

### PR DESCRIPTION
**Pull request by milesgranger**

### CODE REVIEW

**Comment by milesgranger** [comment]
Putting this on the back-burner until it's desired to have by someone.

Because pyO3 does not have a native representation of a file-like object from Python's cffi, it requires multiple calls into Python from Rust which ends up having a significantly slower performance compared to other alternatives.

**Comment by martindurant** [comment]
This was a cool request - is there an issue on py03 tracking it? In fact, I don't see how to use pyo3 to call the python C API at all, but I suppose you can just declare it as an external library?

**Comment by milesgranger** [comment]
I was mainly looking at this issue: https://github.com/PyO3/pyo3/issues/933, but haven't gotten back to playing with this. Possible maybe to implement a buffer protocol in a Rust type that Python can have ownership of. :thinking: But so far as 
```python
with open(...) f: 
    sweet_rust_function(f)
```
doesn't seem like an option right now, unless I misunderstand. But again, will have to look back into this in more depth.

**Comment by milesgranger** [comment]
closing in favor of #45

**Pull request closed without merging**
