### PR TITLE
Support PyPy builds

### PR DESCRIPTION
**Pull request by milesgranger**
Adds PyPy36 support.

- Needs to run `pypy_patch.py` after builds until https://github.com/PyO3/maturin/issues/312 is closed
- Cannot support Windows PyPy until https://github.com/PyO3/maturin/issues/115 is closed

### CODE REVIEW

**Comment by milesgranger** [comment]
@martindurant is this helpful at all for our conda recipe issues? Just missing Window's PyPy...

**Comment by martindurant** [comment]
Good enough for me! I'm not going to stretch too far for pypy, especially since fastparquet, the first user of cramjam, dopesn't run on pypy anyway (because of numba).

**Comment by martindurant** [comment]
As far as conda-forge is concerned, let's release a new version with the allocation updates sooner rather than later. Perhaps should open a new issue of things we'd like to see happen by that release.

**Comment by milesgranger** [comment]
Great, was going to merge this then #26 if you're good with that.
Is it also okay with a `2.0.0-rc2` prerelease, as would still like to do some minor housekeeping; although admittedly nothing that would affect the major/minor version I guess.

**Comment by martindurant** [comment]
> Is it also okay with a 2.0.0-rc2 prerelease

I've never done this. For pydata packages, most just inc the smallest number as seems fit. We don't strictly semantic-version, and indeed many are coving to calendar-version to avoid any confusion.

**Pull request merged**
